--DROP USER PHANHE2 CASCADE;
--CREATE USER PHANHE2 IDENTIFIED BY 1;
--GRANT ALL PRIVILEGES TO PHANHE2;
--GRANT CREATE SESSION TO PHANHE2;
--GRANT DBA TO PHANHE2;
--CONN PHANHE2/1

DROP TABLE NHANSU CASCADE CONSTRAINTS;
DROP TABLE SINHVIEN CASCADE CONSTRAINTS;
DROP TABLE DONVI CASCADE CONSTRAINTS;
DROP TABLE HOCPHAN CASCADE CONSTRAINTS;
DROP TABLE KHMO CASCADE CONSTRAINTS;
DROP TABLE PHANCONG CASCADE CONSTRAINTS;
DROP TABLE DANGKY CASCADE CONSTRAINTS;


CREATE TABLE DONVI (
    MADV VARCHAR2(4), -- DV01
    TENDV VARCHAR2(4) NOT NULL UNIQUE, -- VPK , HTTT, CNPM, KHMT, CNTT, TGMT, MMT
    TRGDV VARCHAR2(5),
    CONSTRAINT DONVI_PK PRIMARY KEY (MADV)

);

CREATE TABLE NHANSU (
    MANV VARCHAR2(5), -- NS102
    HOTEN NVARCHAR2(100) NOT NULL,
    PHAI NVARCHAR2(3) CHECK (LOWER(PHAI) IN ('nam','nữ')), -- NAM/NỮ
    NGSINH DATE,
    PHUCAP NUMBER(6), -- 6 DIGIT 
    DT VARCHAR2(10), -- 10 DIGIT 
    VAITRO NVARCHAR2(20),
    MADV VARCHAR2(4) NOT NULL,
    CONSTRAINT NHANSU_PK PRIMARY KEY (MANV)

);

CREATE TABLE SINHVIEN (
    MASV VARCHAR2(6), -- SVxxxx
    HOTEN NVARCHAR2(100) NOT NULL,
    PHAI NVARCHAR2(3) CHECK (LOWER(PHAI) IN ('nam','nữ')), -- NAM/NỮ
    NGSINH DATE,
    DCHI NVARCHAR2(50),
    DT VARCHAR2(10) , -- 10 DIGIT DT
    MACT VARCHAR2(4) NOT NULL CHECK (MACT IN ('CQ','CLC', 'CTTT','VP')), -- CQ,CLC,CTTT,VP
    MANGANH VARCHAR2(4),CHECK (MANGANH IN ('HTTT','CNPM', 'KHMT','CNTT', 'TGMT', 'MMT')), --  HTTT, CNPM, KHMT, CNTT, TGMT, MMT
    SOTCTL NUMBER(3), --132 TC
    DTBTL NUMBER(4,2), -- 7.2
    CONSTRAINT SINHVIEN_PK PRIMARY KEY (MASV)
    
);

CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(5), -- HP001
    TENHP NVARCHAR2(50) NOT NULL,
    SOTC NUMBER(1),
    STLT NUMBER(1),
    STTH NUMBER(1),
    SOSVTD NUMBER(3),
    MADV VARCHAR2(4) NOT NULL,
    CONSTRAINT HOCPHAN_PK PRIMARY KEY (MAHP),
    CONSTRAINT STTH_STLT_SOTC_CHK CHECK (STTH + STLT = SOTC)

);

CREATE TABLE KHMO (
    KHMO_ID NUMBER(4), 
    MAHP VARCHAR2(6) NOT NULL,
    HK NUMBER(1) NOT NULL, --1,2,3
    NAM VARCHAR2(10) CHECK (NAM LIKE '%-%') NOT NULL, -- Ensures format 'YY-YY' FROM 2014 TO 2024
    MACT VARCHAR2(4) NOT NULL, -- CQ,CLC,CTTT,VP
    CONSTRAINT KHMO_PK PRIMARY KEY(KHMO_ID)
    
);
ALTER TABLE KHMO
ADD CONSTRAINT KHMO_FK_HP
FOREIGN KEY (MAHP)
REFERENCES HOCPHAN(MAHP);

ALTER TABLE KHMO
ADD CONSTRAINT KHMO_UK UNIQUE (MAHP, HK, NAM, MACT);


CREATE TABLE PHANCONG (
    PHANCONG_ID NUMBER(4), 
    MAGV VARCHAR2(5) NOT NULL, --MANV
    MAHP VARCHAR2(5) NOT NULL, -- HPxxx
    HK NUMBER(1) NOT NULL,
    NAM VARCHAR2(10) NOT NULL,
    MACT VARCHAR2(4) NOT NULL, -- CQ,CLC,CTTT,VP
    CONSTRAINT PHANCONG_PK PRIMARY KEY(PHANCONG_ID)

);

ALTER TABLE PHANCONG
ADD CONSTRAINT PHANCONG_FK_KHMO
FOREIGN KEY (MAHP,HK,NAM,MACT)
REFERENCES KHMO(MAHP,HK,NAM,MACT);

ALTER TABLE PHANCONG
ADD CONSTRAINT PHANCONG_UK UNIQUE (MAGV,MAHP, HK, NAM, MACT);

CREATE TABLE DANGKY (
    DANGKY_ID NUMBER(4), 
    MASV VARCHAR2(6) NOT NULL,
    MAGV VARCHAR2(5) NOT NULL,
    MAHP VARCHAR2(5) NOT NULL,
    HK NUMBER(1) NOT NULL,
    NAM VARCHAR2(10) CHECK (NAM LIKE '%-%') NOT NULL, -- Ensures format 'YYYY-YYYY'
    MACT VARCHAR2(4) NOT NULL,
    DIEMTH NUMBER(2), --  20%
    DIEMQT NUMBER(2), -- 30%
    DIEMCK  NUMBER(2), -- 50%
    DIEMTK NUMBER(2,1) CHECK (DIEMTK <= 10),
    CONSTRAINT DANGKY_PK PRIMARY KEY(DANGKY_ID)

);

ALTER TABLE DANGKY
ADD CONSTRAINT DANGKY_FK_PC
FOREIGN KEY (MAGV,MAHP,HK,NAM,MACT)
REFERENCES PHANCONG(MAGV,MAHP,HK,NAM,MACT);

ALTER TABLE DANGKY
ADD CONSTRAINT DANGKY_UK UNIQUE (MASV,MAGV,MAHP, HK, NAM, MACT);



